[build]
  command = "npm run build"
  publish = "dist"

# Define environment variables for the contact form
# These should be set in the Netlify dashboard
[template.environment]
  SMTP_USER = "Your SMTP username"
  SMTP_PASSWORD = "Your SMTP password"
  SMTP_HOST = "smtp.gmail.com"
  SMTP_PORT = "465"
  SMTP_SECURE = "true"
  EMAIL_FROM = "your-email@example.com"
  EMAIL_TO = "your-email@example.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 